In [2]:
from ds_core.paths import (
    RAW_DATA_DIR,
    INTERIM_DATA_DIR,
    PROCESSED_DATA_DIR,
    EXTERNAL_DATA_DIR,
    NOTEBOOKS_DIR,
    OUTPUT_DIR
)

import pandas as pd

In [3]:
df = pd.read_csv(
    RAW_DATA_DIR / "curso_1" / "estatistica_descritiva" / "analise_imoveis_sao_paulo.csv", sep=";", header=0
)

In [4]:
df

,Unnamed: 0,Rua,Bairro,Cidade,area_m2,quartos,banheiros,vagas,price
0,0,"Avenida Itacira, 255",Planalto Paulista,São Paulo,1000,4,8,6,R$ 7.000.000
1,1,"Rua Aurelia Perez Alvarez, 42",Jardim dos Estados,São Paulo,469-524,3-6,3-6,4,R$ 3.700.000
2,2,Rua Alba Valdez,Jardim Reimberg,São Paulo,125,4,3,2,R$ 380.000
3,3,"Jardim Morumbi, São Paulo",SP,NaN,310,3,2,4,R$ 685.000
4,4,"Rua Tobias Barreto, 195",Mooca,São Paulo,100,3,2,2,R$ 540.000
...,...,...,...,...,...,...,...,...,...
10028,10028,Rua Tapuçu,Vila Sofia,São Paulo,90,2,2,2,R$ 665.000
10029,10029,Rua Guararema,Bosque da Saúde,São Paulo,600,8,7,5,R$ 2.300.000
10030,10030,Rua Estero Belaco,Vila da Saúde,São Paulo,200,3,3,6,R$ 1.050.000
10031,10031,"Rua Manuel Onha, , 514",Vila Oratório,São Paulo,180,3,2,2,R$ 2.200\n /Mês
10032,10032,"Rua Barão de Tramandaí, 0",Vila Alpina,São Paulo,117,3,2,2,R$ 270.000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10033 entries, 0 to 10032
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10033 non-null  int64
 1   Rua         10033 non-null  str
 2   Bairro      10033 non-null  str
 3   Cidade      6559 non-null   str
 4   area_m2     10033 non-null  str
 5   quartos     10033 non-null  str
 6   banheiros   10033 non-null  str
 7   vagas       10033 non-null  str
 8   price       10033 non-null  str
dtypes: int64(1), str(8)
memory usage: 705.6 KB

In [6]:
df.sample(n=100)

,Unnamed: 0,Rua,Bairro,Cidade,area_m2,quartos,banheiros,vagas,price
4020,4020,Rua Domingos Barreto,Jardim Everest,São Paulo,500,4,5,6,R$ 20.000\n /Mês
6636,6636,Rua Matilde Diez,Vila do Castelo,São Paulo,453,3,1,5,R$ 780.000
4042,4042,"Jardim Europa, São Paulo",SP,NaN,450,4,5,4,R$ 8.500.000
4400,4400,"Rua Comandante Ismael Guilherme, , 537",Jardim Luzitânia,São Paulo,600,3,5,4,R$ 12.000.000
9154,9154,Avenida Morumbi,Morumbi,São Paulo,670,4,7,8,R$ 2.000.000
...,...,...,...,...,...,...,...,...,...
6091,6091,Rua Elizabeth Trovão Usui,Vila Olímpia,São Paulo,111,3,2,2,R$ 1.600.000
3591,3591,Rua Croata,Vila Ipojuca,São Paulo,141,2,2,1,R$ 1.190.000
4790,4790,Rua Valença,Sumaré,São Paulo,280,4,7,3,R$ 2.600.000
4777,4777,"Cidade Jardim, São Paulo",SP,NaN,380,3,5,4,R$ 4.000.000
6235,6235,Rua João Batista Leme da Silva,Vila Madalena,São Paulo,174,4,4,2,R$ 1.219.000

In [7]:
colunas = list(df.columns)

for coluna in colunas:
    print(f"Percentual de linhas com valor nulo na coluna '{coluna}': {df[coluna].isnull().mean() * 100:.2f}%")

Percentual de linhas com valor nulo na coluna 'Unnamed: 0': 0.00%
Percentual de linhas com valor nulo na coluna 'Rua': 0.00%
Percentual de linhas com valor nulo na coluna 'Bairro': 0.00%
Percentual de linhas com valor nulo na coluna 'Cidade': 34.63%
Percentual de linhas com valor nulo na coluna 'area_m2': 0.00%
Percentual de linhas com valor nulo na coluna 'quartos': 0.00%
Percentual de linhas com valor nulo na coluna 'banheiros': 0.00%
Percentual de linhas com valor nulo na coluna 'vagas': 0.00%
Percentual de linhas com valor nulo na coluna 'price': 0.00%

In [22]:
colunas_usadas = [column for column in df.columns if column != "Unnamed: 0"]

df_duplicados = df.groupby(colunas_usadas, as_index=False).size()
df_duplicados[df_duplicados["size"] > 1]

Empty DataFrame
Columns: [Rua, Bairro, Cidade, area_m2, quartos, banheiros, vagas, price, size]
Index: []

In [18]:
df = df.drop(columns=["Unnamed: 0"]).drop_duplicates()