In [1]:
from ds_core.paths import (
    RAW_DATA_DIR,
    INTERIM_DATA_DIR,
    PROCESSED_DATA_DIR,
    EXTERNAL_DATA_DIR,
    NOTEBOOKS_DIR,
    OUTPUT_DIR
)

import pandas as pd

In [3]:
df = pd.read_csv(
    RAW_DATA_DIR / "curso_1" / "estatistica_descritiva" / "ifood_restaurants_november_2020.csv", sep=",", header=0
)

In [8]:
df

,avatar,category,delivery_fee,delivery_time,distance,name,price_range,rating,url,lat,long
0,https://static-images.ifood.com.br/image/uploa...,Lanches,9.00,80,6.20,El'moedor,CHEAP,4.30303,https://www.ifood.com.br/delivery/vitoria-de-s...,-8.11298,-35.2150
1,https://static-images.ifood.com.br/image/uploa...,Doces & Bolos,6.00,35,3.03,Delicia de Brigadeiro,CHEAPEST,0.00000,https://www.ifood.com.br/delivery/moreno-pe/de...,-8.11298,-35.1150
2,https://static-images.ifood.com.br/image/uploa...,Brasileira,4.00,40,1.51,Pizzaria Rappi10 - Moreno,CHEAPEST,0.00000,https://www.ifood.com.br/delivery/moreno-pe/pi...,-8.11298,-35.1150
3,https://static-images.ifood.com.br/image/uploa...,Lanches,0.00,50,0.79,Tapioca Arretada,CHEAPEST,5.00000,https://www.ifood.com.br/delivery/jaboatao-dos...,-8.11298,-35.0150
4,https://static-images.ifood.com.br/image/uploa...,Salgados,12.99,36,5.12,Minuto Kit Festa ( Salgados e Doces ),CHEAPEST,5.00000,https://www.ifood.com.br/delivery/jaboatao-dos...,-8.11298,-35.0150
...,...,...,...,...,...,...,...,...,...,...,...
361442,https://static-images.ifood.com.br/image/uploa...,Brasileira,3.99,18,1.66,Restaurante Nosso Tempero,CHEAPEST,0.00000,https://www.ifood.com.br/delivery/campos-do-jo...,-22.72960,-45.5833
361443,https://static-images.ifood.com.br/image/uploa...,Lanches,3.99,18,1.70,Belgian Waffles,CHEAPEST,0.00000,https://www.ifood.com.br/delivery/campos-do-jo...,-22.72960,-45.5833
361444,https://static-images.ifood.com.br/image/uploa...,Pizza,8.00,45,1.34,Sabor de Campos Pizzaria e Restaurante,CHEAPEST,0.00000,https://www.ifood.com.br/delivery/campos-do-jo...,-22.72960,-45.5833
361445,https://static-images.ifood.com.br/image/uploa...,Cafeteria,1.00,35,0.20,Maria Bonita,CHEAPEST,0.00000,https://www.ifood.com.br/delivery/campos-novos...,-27.40020,-51.2276
361446,https://static-images.ifood.com.br/image/uploa...,Doces & Bolos,0.00,60,0.96,Cacau Show - Supermercado Campos Salles,CHEAPEST,5.00000,https://www.ifood.com.br/delivery/campos-sales...,-7.06761,-40.3687

In [6]:
df.dtypes

avatar               str
category             str
delivery_fee     float64
delivery_time      int64
distance         float64
name                 str
price_range          str
rating           float64
url                  str
lat              float64
long             float64
dtype: object

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 361447 entries, 0 to 361446
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   avatar         361149 non-null  str
 1   category       361447 non-null  str
 2   delivery_fee   361447 non-null  float64
 3   delivery_time  361447 non-null  int64
 4   distance       361447 non-null  float64
 5   name           361447 non-null  str
 6   price_range    361447 non-null  str
 7   rating         361447 non-null  float64
 8   url            361447 non-null  str
 9   lat            361447 non-null  float64
 10  long           361447 non-null  float64
dtypes: float64(5), int64(1), str(5)
memory usage: 30.3 MB

In [ ]:
df.select_dtypes(include=["number"])

        delivery_fee  delivery_time  distance   rating       lat     long
0               9.00             80      6.20  4.30303  -8.11298 -35.2150
1               6.00             35      3.03  0.00000  -8.11298 -35.1150
2               4.00             40      1.51  0.00000  -8.11298 -35.1150
3               0.00             50      0.79  5.00000  -8.11298 -35.0150
4              12.99             36      5.12  5.00000  -8.11298 -35.0150
...              ...            ...       ...      ...       ...      ...
361442          3.99             18      1.66  0.00000 -22.72960 -45.5833
361443          3.99             18      1.70  0.00000 -22.72960 -45.5833
361444          8.00             45      1.34  0.00000 -22.72960 -45.5833
361445          1.00             35      0.20  0.00000 -27.40020 -51.2276
361446          0.00             60      0.96  5.00000  -7.06761 -40.3687

[361447 rows x 6 columns]

In [15]:
df.select_dtypes(include=["object", "category"])

C:\Users\matheus.belmonte\AppData\Local\Temp\ipykernel_19068\3885210318.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=["object", "category"])

,avatar,category,name,price_range,url
0,https://static-images.ifood.com.br/image/uploa...,Lanches,El'moedor,CHEAP,https://www.ifood.com.br/delivery/vitoria-de-s...
1,https://static-images.ifood.com.br/image/uploa...,Doces & Bolos,Delicia de Brigadeiro,CHEAPEST,https://www.ifood.com.br/delivery/moreno-pe/de...
2,https://static-images.ifood.com.br/image/uploa...,Brasileira,Pizzaria Rappi10 - Moreno,CHEAPEST,https://www.ifood.com.br/delivery/moreno-pe/pi...
3,https://static-images.ifood.com.br/image/uploa...,Lanches,Tapioca Arretada,CHEAPEST,https://www.ifood.com.br/delivery/jaboatao-dos...
4,https://static-images.ifood.com.br/image/uploa...,Salgados,Minuto Kit Festa ( Salgados e Doces ),CHEAPEST,https://www.ifood.com.br/delivery/jaboatao-dos...
...,...,...,...,...,...
361442,https://static-images.ifood.com.br/image/uploa...,Brasileira,Restaurante Nosso Tempero,CHEAPEST,https://www.ifood.com.br/delivery/campos-do-jo...
361443,https://static-images.ifood.com.br/image/uploa...,Lanches,Belgian Waffles,CHEAPEST,https://www.ifood.com.br/delivery/campos-do-jo...
361444,https://static-images.ifood.com.br/image/uploa...,Pizza,Sabor de Campos Pizzaria e Restaurante,CHEAPEST,https://www.ifood.com.br/delivery/campos-do-jo...
361445,https://static-images.ifood.com.br/image/uploa...,Cafeteria,Maria Bonita,CHEAPEST,https://www.ifood.com.br/delivery/campos-novos...
361446,https://static-images.ifood.com.br/image/uploa...,Doces & Bolos,Cacau Show - Supermercado Campos Salles,CHEAPEST,https://www.ifood.com.br/delivery/campos-sales...

In [22]:
numéricas = df.select_dtypes(include=['number']).columns.tolist()
categóricas = df.select_dtypes(include=['object', 'category']).columns.tolist()

print("Variáveis numéricas:", numéricas)
print("Variáveis categóricas:", categóricas)

Variáveis numéricas: ['delivery_fee', 'delivery_time', 'distance', 'rating', 'lat', 'long']
Variáveis categóricas: ['avatar', 'category', 'name', 'price_range', 'url']

C:\Users\matheus.belmonte\AppData\Local\Temp\ipykernel_19068\1724802777.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categóricas = df.select_dtypes(include=['object', 'category']).columns.tolist()

In [23]:
df['price_range'].unique()

<StringArray>
['CHEAP', 'CHEAPEST', 'MODERATE', 'EXPENSIVE', 'MOST_EXPENSIVE']
Length: 5, dtype: str

In [24]:
df['category'].unique()

<StringArray>
[        'Lanches',   'Doces & Bolos',      'Brasileira',        'Salgados',
         'Marmita',         'Bebidas',            'Açaí',    'Conveniência',
      'Hambúrguer',          'Pastel',        'Japonesa',           'Pizza',
        'Saudável',         'Variada',   'Frutos Do Mar',  'Cozinha Rápida',
          'Carnes',        'Italiana',         'Mercado',  'Congelados Fit',
         'Padaria',         'Chinesa',           'Crepe',   'Contemporânea',
       'Cafeteria',        'Sorvetes',           'Árabe',         'Peruana',
      'Nordestina',        'Francesa',      'Congelados',         'Frangos',
    'Mediterrânea',           'Alemã',     'Vegetariana',        'Panqueca',
      'Portuguesa',        'Mexicana',          'Vegana',        'Asiática',
   'Casa de Sucos',        'Africana',  'Sopas & Caldos',         'Tapioca',
       'Argentina',       'Espanhola',         'Coreana',        'Yakisoba',
      'Tailandesa',          'Peixes',         'Mineira',         'Indiana',
       'Presentes',          'Baiana',      'Colombiana',             'Xis',
 'Típica do Norte',          'Gaúcha',      'Paranaense',           'Grega',
 'Churrasco Grego']
Length: 61, dtype: str